# Generated by Django 3.0.7 on 2021-02-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notes',
            unique_together={('student', 'subject')},
        ),
    ]
