# Generated by Django 3.0.7 on 2021-02-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210225_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='coef',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
